//HintName: IC.Dummy.GetUsersQueryCache.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Dummy;

partial class GetUsersQueryCache : global::Immediate.Cache.Shared.ApplicationCache<
	global::Dummy.GetUsersQuery.Query,
	global::Dummy.GetUsersQuery.Response
>
{
	public GetUsersQueryCache(
		global::Microsoft.Extensions.Caching.Memory.IMemoryCache memoryCache,
		global::Immediate.Cache.Shared.Owned<
			global::Immediate.Handlers.Shared.IHandler<
				global::Dummy.GetUsersQuery.Query,
				global::Dummy.GetUsersQuery.Response
			>
		> ownedHandler
	) : base(memoryCache, ownedHandler)
	{
	}
}
