//HintName: IC.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class CacheServiceCollectionExtensions
{
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddCustomCaches(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Add(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
				typeof(global::Dummy.GetUsersQueryCache),
				typeof(global::Dummy.GetUsersQueryCache)
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
				typeof(global::Immediate.Cache.Shared.Owned<>),
				typeof(global::Immediate.Cache.Shared.Owned<>)
			)
		);

		return services;
	}
}
