<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<IsPackable>true</IsPackable>
	<IncludeBuildOutput>false</IncludeBuildOutput>

	<EnablePackageValidation>true</EnablePackageValidation>
	<PackageValidationBaselineVersion>2.0.0</PackageValidationBaselineVersion>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
	<Title>Immediate.Cache</Title>
	<Description>A collection of classes that simplify caching responses from Immediate.Handlers handlers.</Description>

	<Authors>Immediate.Cache Developers</Authors>
	<Copyright>© 2024-2026 Immediate.Cache Developers</Copyright>

	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageReadmeFile>readme.md</PackageReadmeFile>
	<PackageTags>csharp-sourcegenerator;caching;immediate-platform</PackageTags>

	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<RepositoryUrl>https://github.com/ImmediatePlatform/Immediate.Cache</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Immediate.Handlers" />
	<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" NoWarn="NU5104" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" NoWarn="NU5104" />
  </ItemGroup>

  <!--
	This ensures the library will be packaged as a source generator when we use `dotnet pack`
	-->
  <ItemGroup>
	<None Include="../../readme.md" Pack="true" PackagePath="/" />

	<!-- IH.Shared -->
	<TfmSpecificPackageFile
	  Include="../Immediate.Cache.Shared/bin/$(Configuration)/$(TargetFramework)/Immediate.Cache.Shared.dll"
	  Pack="true"
	  PackagePath="lib/$(TargetFramework)" />

	<TfmSpecificPackageFile
	  Include="../Immediate.Cache.Shared/bin/$(Configuration)/$(TargetFramework)/Immediate.Cache.Shared.xml"
	  Pack="true"
	  PackagePath="lib/$(TargetFramework)" />
  </ItemGroup>

  <ItemGroup>
	<None
	  Include="../Immediate.Cache.Analyzers/bin/$(Configuration)/roslyn4.8/Immediate.Cache.Analyzers.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn4.8/cs" />

	<None
	  Include="../Immediate.Cache.Generators/bin/$(Configuration)/roslyn4.8/Immediate.Cache.Generators.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn4.8/cs" />
  </ItemGroup>

  <ItemGroup>
	<None
	  Include="../Immediate.Cache.Analyzers/bin/$(Configuration)/roslyn5.0/Immediate.Cache.Analyzers.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn5.0/cs" />

	<None
	  Include="../Immediate.Cache.Generators/bin/$(Configuration)/roslyn5.0/Immediate.Cache.Generators.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn5.0/cs" />

	<TfmSpecificPackageFile
	  Condition=" '$(TargetFramework)' == 'net8.0' "
	  Include="$(PkgScriban)/lib/net8.0/Scriban.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn5.0/cs" />
  </ItemGroup>

  <ItemGroup>
	<None
	  Include="../Immediate.Cache.Analyzers/bin/$(Configuration)/roslyn5.9/Immediate.Cache.Analyzers.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn5.9/cs" />

	<None
	  Include="../Immediate.Cache.Generators/bin/$(Configuration)/roslyn5.9/Immediate.Cache.Generators.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn5.9/cs" />

	<TfmSpecificPackageFile
	  Condition=" '$(TargetFramework)' == 'net8.0' "
	  Include="$(PkgScriban)/lib/net8.0/Scriban.dll"
	  Pack="true"
	  PackagePath="analyzers/dotnet/roslyn5.9/cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Scriban" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="../Immediate.Cache.Shared/Immediate.Cache.Shared.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <PropertyGroup>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net8.0' ">roslyn4.8</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net10.0' ">roslyn5.0</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net11.0' ">roslyn5.9</RoslynVersion>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Cache.Analyzers/Immediate.Cache.Analyzers.csproj" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>

	<ProjectReference Include="../../src/Immediate.Cache.Generators/Immediate.Cache.Generators.csproj" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>
  </ItemGroup>

</Project>
